In [1]:
import numpy as np
# we dont have real data: we have to generate data 
# note: you are always going to be getting real data from either kaggle or hugging face

np.random.seed(42)
# 1, 2, 4
# 2,3,5
# 3, 6, 8
# it might lead to model inconsistency
# seed is going to generate only once and you can always fit in your model

# we want to create a model that predict the house price given the house size

# generate data for the size

In [4]:
size=np.random.randint(50, 201, 20) 
price=0.3 * size * np.random.normal(0, 2, 20)
# eg first value of price=> 0.3*152 *0.5=
print(size)
print(price)

[ 70 107  71 138  98 108  64 100 157 104 113 180 100 184  70 122  67 181
 138 109]
[-85.12222386  71.86699586  33.19360623 -91.17089423  66.4574178
  24.17810567 -14.8405613  -69.52621452  53.32782828 -43.9578953
 -93.4242848  -38.13659842 -27.68794309   7.35896355  -7.4039978
  87.90535091  28.07563744 -18.63889151 -75.11504884  77.73612251]

In [5]:
# we have to store data in dictionary format:
data={
    "size":size,
    "price":price
}

data

{'size': array([ 70, 107,  71, 138,  98, 108,  64, 100, 157, 104, 113, 180, 100,
        184,  70, 122,  67, 181, 138, 109], dtype=int32),
 'price': array([-85.12222386,  71.86699586,  33.19360623, -91.17089423,
         66.4574178 ,  24.17810567, -14.8405613 , -69.52621452,
         53.32782828, -43.9578953 , -93.4242848 , -38.13659842,
        -27.68794309,   7.35896355,  -7.4039978 ,  87.90535091,
         28.07563744, -18.63889151, -75.11504884,  77.73612251])}

In [8]:
# use pandas to convert data into table format: (python library use to manipulated data in table format)
import pandas as pd
# converting data into table format is called dataframes
df=pd.DataFrame(data)

df

    size      price
0     70 -85.122224
1    107  71.866996
2     71  33.193606
3    138 -91.170894
4     98  66.457418
5    108  24.178106
6     64 -14.840561
7    100 -69.526215
8    157  53.327828
9    104 -43.957895
10   113 -93.424285
11   180 -38.136598
12   100 -27.687943
13   184   7.358964
14    70  -7.403998
15   122  87.905351
16    67  28.075637
17   181 -18.638892
18   138 -75.115049
19   109  77.736123

In [11]:
# 1. Inspect the data
df.head()
df.tail()

    size      price
15   122  87.905351
16    67  28.075637
17   181 -18.638892
18   138 -75.115049
19   109  77.736123

In [12]:
# How can we get the target and the featurtes from the data set
X=df["size"]
X

0      70
1     107
2      71
3     138
4      98
5     108
6      64
7     100
8     157
9     104
10    113
11    180
12    100
13    184
14     70
15    122
16     67
17    181
18    138
19    109
Name: size, dtype: int32