## Q3. Pandas DataFrame Surgery

In [2]:
import numpy as np
import pandas as pd



df=pd.DataFrame({
    'name':['Alice', 'Bob', 'Carlson', 'Diana','Eve'],
    'score':[88, 72, 95, 61, 83],
    'passed':[True, True, True, False, True]
})

df

      name  score  passed
0    Alice     88    True
1      Bob     72    True
2  Carlson     95    True
3    Diana     61   False
4      Eve     83    True

In [5]:
# np.select is the vectorised if/elif/else — much faster than a Python loop
# conditions are checked in ORDER; the first True match wins

conditions=[df['score']>=90, df['score']>=80]
conditions
choices=['A', 'B']
df['grades']=np.select(conditions, choices, default='C')
df

      name  score  passed grades
0    Alice     88    True      B
1      Bob     72    True      C
2  Carlson     95    True      A
3    Diana     61   False      C
4      Eve     83    True      B

In [9]:
passing=df[df['passed']]
passing

      name  score  passed grades
0    Alice     88    True      B
1      Bob     72    True      C
2  Carlson     95    True      A
4      Eve     83    True      B

In [10]:
print(df['score'].describe())

count     5.00000
mean     79.80000
std      13.44247
min      61.00000
25%      72.00000
50%      83.00000
75%      88.00000
max      95.00000
Name: score, dtype: float64