In [2]:
import numpy as np

data = np.array([
 [34.2, 220.1, 1.20], # time step 0
 [35.8, 219.5, 1.35], # time step 1
 [38.1, 221.0, 1.50], # time step 2
 [40.3, 218.8, 1.68], # time step 3
 [39.7, 220.5, 1.60], # time step 4
])

data

array([[ 34.2 , 220.1 ,   1.2 ],
       [ 35.8 , 219.5 ,   1.35],
       [ 38.1 , 221.  ,   1.5 ],
       [ 40.3 , 218.8 ,   1.68],
       [ 39.7 , 220.5 ,   1.6 ]])

In [4]:
print(data.shape)

(5, 3)

In [6]:
print(data[:, 0])
print(data[1:3, :])

[34.2 35.8 38.1 40.3 39.7]
[[ 35.8  219.5    1.35]
 [ 38.1  221.     1.5 ]]

In [7]:
print(data.mean(axis=0))

[ 37.62  219.98    1.466]

In [12]:
import pandas as pd
import numpy as np
# ─── CREATING A DATAFRAME FROM A DICTIONARY ──────────────────────────
# Keys become column names; values are lists of column data
df = pd.DataFrame({
 "timestamp": pd.date_range("2025-06-01 09:00", periods=6, freq="5min"),
 "temperature": [34.2, 35.8, 38.1, 40.3, 39.7, 36.5],
 "voltage": [220.1, 219.5, 221.0, 218.8, 220.5, 220.0],
 "current": [1.20, 1.35, 1.50, 1.68, 1.60, 1.40],
 "status": ["ok", "ok", "warn", "crit", "warn", "ok"],
})

df

            timestamp  temperature  voltage  current status
0 2025-06-01 09:00:00         34.2    220.1     1.20     ok
1 2025-06-01 09:05:00         35.8    219.5     1.35     ok
2 2025-06-01 09:10:00         38.1    221.0     1.50   warn
3 2025-06-01 09:15:00         40.3    218.8     1.68   crit
4 2025-06-01 09:20:00         39.7    220.5     1.60   warn
5 2025-06-01 09:25:00         36.5    220.0     1.40     ok

In [13]:
df.set_index("timestamp", inplace=True)

In [20]:
df.replace("timestamp", "time")
df

                     temperature  voltage  current status
timestamp
2025-06-01 09:00:00         34.2    220.1     1.20     ok
2025-06-01 09:05:00         35.8    219.5     1.35     ok
2025-06-01 09:10:00         38.1    221.0     1.50   warn
2025-06-01 09:15:00         40.3    218.8     1.68   crit
2025-06-01 09:20:00         39.7    220.5     1.60   warn
2025-06-01 09:25:00         36.5    220.0     1.40     ok

In [21]:
print(df.describe())

       temperature     voltage   current
count     6.000000    6.000000  6.000000
mean     37.433333  219.983333  1.455000
std       2.357682    0.767898  0.174786
min      34.200000  218.800000  1.200000
25%      35.975000  219.625000  1.362500
50%      37.300000  220.050000  1.450000
75%      39.300000  220.400000  1.575000
max      40.300000  221.000000  1.680000

In [22]:
print(df.info())

<class 'pandas.DataFrame'>
DatetimeIndex: 6 entries, 2025-06-01 09:00:00 to 2025-06-01 09:25:00
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   temperature  6 non-null      float64
 1   voltage      6 non-null      float64
 2   current      6 non-null      float64
 3   status       6 non-null      str
dtypes: float64(3), str(1)
memory usage: 240.0 bytes
None

In [23]:
temps = df["temperature"]

In [26]:
temps

timestamp
2025-06-01 09:00:00    34.2
2025-06-01 09:05:00    35.8
2025-06-01 09:10:00    38.1
2025-06-01 09:15:00    40.3
2025-06-01 09:20:00    39.7
2025-06-01 09:25:00    36.5
Name: temperature, dtype: float64

In [37]:
df.loc[df.index[3], "current"]=None

df

                     temperature  voltage  current status
timestamp
2025-06-01 09:00:00         34.2    220.1     1.20     ok
2025-06-01 09:05:00         35.8    219.5     1.35     ok
2025-06-01 09:10:00         38.1    221.0     1.50   warn
2025-06-01 09:15:00         40.3    218.8      NaN   crit
2025-06-01 09:20:00         39.7    220.5     1.60   warn
2025-06-01 09:25:00         36.5    220.0     1.40     ok

In [39]:
df.isnull().sum()

temperature    0
voltage        0
current        1
status         0
dtype: int64

In [43]:
df["current"] = df["current"].fillna(df["current"].mean())
df

                     temperature  voltage  current status
timestamp
2025-06-01 09:00:00         34.2    220.1     1.20     ok
2025-06-01 09:05:00         35.8    219.5     1.35     ok
2025-06-01 09:10:00         38.1    221.0     1.50   warn
2025-06-01 09:15:00         40.3    218.8     1.41   crit
2025-06-01 09:20:00         39.7    220.5     1.60   warn
2025-06-01 09:25:00         36.5    220.0     1.40     ok